### ISSUE TITLE
Console does not show stacktrace for uncaught exceptions.

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode-js-debug#1013]
**Description**
I am using an Electron configuration with a main process accessed using node launch and a renderer process using chrome attach. When an uncaught exception is thrown in the renderer, the VSCode console does not have a stacktrace. If the exception is caught and manually logged, it shows the stacktrace as "arg0". The browser console (opened with F12 in Electron) has the full stacktrace. The behavior is as expected using the legacy debugger.

**Files**
[vscode-debugadapter-3b997500.json.gz](https://github.com/microsoft/vscode-js-debug/files/6565060/vscode-debugadapter-3b997500.json.gz) (Launcher log)
[vscode-debugadapter-84f1a0a3.json.gz](https://github.com/microsoft/vscode-js-debug/files/6565061/vscode-debugadapter-84f1a0a3.json.gz) (Renderer log)
[launch.zip](https://github.com/microsoft/vscode-js-debug/files/6528139/launch.zip) (Launch configuration)

**Versions**
VSCode: 1.56.2
Node.js: 14.16.0
Electron: 12.0.9
Debugger for Chrome 4.12.12

**Comment by connor4312** [comment]
Thanks for the issue, duplicates https://github.com/microsoft/vscode/issues/122870

**Comment by DJ4ddi** [comment]
I'm not confident that this is a duplicate. My issue is that the "arg0" doesn't show up at all (rather than just not being displayed correctly).

**Comment by connor4312** [comment]
Can you grab a trace log using the instructions in the issue template?

**Comment by DJ4ddi** [comment]
Done, see [launcher](https://github.com/microsoft/vscode-js-debug/files/6565060/vscode-debugadapter-3b997500.json.gz) and [renderer](https://github.com/microsoft/vscode-js-debug/files/6565061/vscode-debugadapter-84f1a0a3.json.gz) logs.

**Comment by connor4312** [comment]
Okay, thanks. I can confirm that this is the same underyling issue; the stack is there...

```
get @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:1146:42
migrateData @ F:\Archive\Code\Repositories\Git\FVTT TDE5\dist\module\migration.js:13:42
<anonymous> @ F:\Archive\Code\Repositories\Git\FVTT TDE5\dist\tde5e.js:120:31
◀ async function ▶
_call @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:194:14
callAll @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:153:12
setupGame @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:4302:11
◀ async function ▶
_initializeGameView @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:5112:16
_initializeView @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:5088:21
initialize @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:4197:16
◀ async function ▶
window.addEventListener.once @ C:\Program Files\FoundryVTT\resources\app\public\scripts\foundry.js:52368:8
```

It's just chopped in the UI.

**Comment by liesauer** [comment]
this issue still exists
![image](https://user-images.githubusercontent.com/8676741/184474357-ea10ce86-5fda-4c9e-9555-cbe2fc1d58da.png)

vsc version: 1.70.0

**Comment by connor4312** [comment]
Everything seems to be working correctly in your screenshot, @liesauer

**Comment by liesauer** [comment]
@connor4312 the location should be clickable like this so we can quick jump to that location.
![微信图片_20220815093415](https://user-images.githubusercontent.com/8676741/184563704-f0df174b-3a4a-49bb-b081-823c497615bd.png)
