### ISSUE TITLE
Last line of multiline strings in debug console not shown

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode-js-debug#1141]
**To Reproduce**
1. Start a debug session and open the debug console
2. Type `"one\ntwo\nthree"` and press enter
3. Observe the echoed output is
   ```
   'one
   two
   ```

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3277153/142686510-18ff44bc-5e33-4a18-8515-f66986ccd5af.png">

**Log File**

**VS Code Version:**

Version: 1.63.0-insider
Commit: d450b04c783dfa6f83dc439017767acccd4e9fac
Date: 2021-11-17T07:45:14.150Z (2 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

Node used in debug session: 16.13.0.

**Comment by connor4312** [comment]
I believe this got fixed with my work around multiline errors last iteration.

**Comment by andrewbranch** [comment]
@connor4312 this is either happening again or still happening

<img width="115" alt="image" src="https://user-images.githubusercontent.com/3277153/163069301-3fd0e8a9-c288-4a2b-b2dd-beb1a4b2f066.png">

**Comment by andrewbranch** [comment]
Version: 1.67.0-insider
Commit: 6ea335e334b90a9aca753d558dec1d14741eff1e
Date: 2022-04-08T05:18:35.034Z (4 days ago)
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0

**Comment by connor4312** [comment]
I don't reproduce this, does it only happen if you log certain things before the string? / do you have a reliable repro?

**Comment by andrewbranch** [comment]
1. New JS Debug Terminal
2. `node`
3. Swap to debug console
4. `'a\nb'`

**Comment by connor4312** [comment]
Hm, seems like sitting on the issue and trying again didn't make me reproduce it 😕  Could you grab some logs? I should be able to diff those and see what's up.

/jsDebugLogs

**Comment by andrewbranch** [comment]
How do I get logs?

**Comment by andrewbranch** [comment]
This is probably helpful. It appears to be a style issue. (So I assume this is the wrong repo to file against.)

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/3277153/173108039-931a8f88-a949-4589-9e3e-f90f2a75baa7.png">

**Comment by andrewbranch** [comment]
There are a few elements with their `style.height` set to an explicit pixel value. If I bump up those values, the result is no longer clipped. So it’s not just a style issue per se, but more likely, something is not communicating the correct number of lines to the renderer.

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/3277153/173108747-9644bfe9-3140-4803-b5e8-a7b0faa47ac1.png">
