### ISSUE TITLE
ECONNREFUSED when Chrome launches with a "Restore pages?" prompt

### ISSUE THREAD

**Issue by nsilvestri** [microsoft/vscode-js-debug#1184]
**Describe the bug**

When launching Chrome with the debugger, if Chrome didn't shut down correctly previously, it will launch with an empty page and display a "Restore pages?" prompt. The browser window will then close automatically after about 5 seconds, and the debugger/VSCode displays an error similar to `Error running browserasd: connect ECONNREFUSED 127.0.0.1:56832`. This cycle will last indefinitely, until the user closes the prompt within the 5 seconds before the window automatically closes, at which point the debugger+Chrome instance will behave normally.

**To Reproduce**
1. Force Chrome to not shut down correctly
2. Launch a Chrome debugging instance through VS Code
4. See error `Error running browserasd: connect ECONNREFUSED 127.0.0.1:56832`

**Log File**

Unable to provide, since I can't get Chrome to crash again.

**VS Code Version:** 1.63.2

**Additional context**

My launch configuration is
```
{
    "type": "pwa-chrome",
    "request": "launch",
    "name": "Launch Chrome against localhost",
    "url": "http://localhost:3000",
    "webRoot": "${workspaceFolder}",
    "userDataDir": "${workspaceFolder}/.vscode/vscode-chrome-debug-userdatadir"
}
```

Possibly related to #930.

**Comment by connor4312** [comment]
I wasn't able to reproduce this. Are you running Chrome via a remote (on ssh or wsl)?

**Comment by nsilvestri** [comment]
I'm not sure if I understand you correctly, but Chrome and VS Code are local connected to WSL where I have node (versus Chrome/VS Code running from the WSL distro instance, if that's the distinction made here)

**Comment by connor4312** [comment]
I think this is fixed. The browser connection via remotes is now much more durable. Tested via `pkill -9 Chrome`. Let me know if you hit this again. Thanks!

**Comment by duckyb** [comment]
@connor4312 this issue still persists

[vscode-debugadapter-f0ef515e.json.gz](https://github.com/microsoft/vscode-js-debug/files/8384960/vscode-debugadapter-f0ef515e.json.gz)

![image](https://user-images.githubusercontent.com/27895007/160952442-9bdba384-ce3e-4562-88df-445cac41905a.png)

Please, let me know if additional info is required.

**Comment by dan-sproutward** [comment]
I am also getting this same issue. I disabled all my extensions and used the nightly Insiders build. I am running vs code from the windows desktop and I am developing using WSL2 with Ubuntu

![image](https://user-images.githubusercontent.com/56736126/168453817-302f2904-8758-4be2-baa5-ab72b42cf5c9.png)
![image](https://user-images.githubusercontent.com/56736126/168453821-f5b9cc26-7df6-46a6-8c49-9c05e610ac06.png)
![image](https://user-images.githubusercontent.com/56736126/168453829-ca316ec1-1d7d-4339-a3a0-a48a5cb9cc2d.png)
![image](https://user-images.githubusercontent.com/56736126/168453886-ae4d57b7-fd3e-418a-92ea-b3dd4a17f0ca.png)

Both of these configurations do not work most of the time. Occasionally, it works but not often enough so that I had to start troubleshooting the issue.
{
      "name": "Next.js: debug client-side",
      "type": "pwa-chrome",
      "request": "launch",
      "url": "http://localhost:3000"
    },
    {
      "name": "Next.js: debug full stack",
      "type": "node-terminal",
      "request": "launch",
      "command": "npm run dev",
      "serverReadyAction": {
        "pattern": "started server on .+, url: (https?://.+)",
        "uriFormat": "%s",
        "action": "debugWithChrome"
      }
    }
