### ISSUE TITLE
Cannot view local variables

### ISSUE THREAD

**Issue by vcellu** [microsoft/vscode-js-debug#1345]
**Describe the bug**
In the variables pane while debugging, the variables are not showing.  Instead get the following error.  This used to work for me for years.

**To Reproduce**
1. Debug any js projects
2. Create a breakpoint or just console.log the object
3. See error

I get the following error
Error processing variables: TypeError: Cannot read properties of undefined (reading 'value')
    at I.createObjectPropertyVars (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:963193)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Q.getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:971272)
    at n.getVariables (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:973664)
    at F._onVariables (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:841871)
    at t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1077296)

**Log File**

**VS Code Version:
Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z (1 wk ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

**Comment by connor4312** [comment]
I'm guessing you're on a pretty old version of Node or a browser/runtime. This is already fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension).

**Comment by vcellu** [comment]
I don't understand, I have node v18.  I'm trying to debug node.js

**Comment by vcellu** [comment]
I updated to the nightly extension.  I still receive this error.

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template
