### ISSUE TITLE
Debugger may hang if a firewall is active

### ISSUE THREAD

**Issue by tusharsnx** [microsoft/vscode-js-debug#2004]
**Describe the bug**

https://github.com/microsoft/vscode-js-debug/blob/6e29d1de451b2949477d15bcdb126187a16fd93b/src/common/findOpenPortSync.ts#L32

The vscode js debugger seems to use `nc` (netcat) for testing arbitrary ports to be available for the debugger to use. This works fine, except when a firewall is active on the system which can block access to ports in a way where the application would never see a reply coming back so they would just hang. In this case, `nc` never receives a reply and keeps waiting for it , and the debugger blocks on that (until it eventually times out).

I'm using WSL's new `networkingMode=mirrored` mode that comes with a firewall that by default blocks requests in the way I described above (no reply sent). I think it's important to wrap the call with a reasonable timeout that is also small. `nc` does give an option to set a timeout with `-w` option. This should be set within a range of a few seconds.

**To Reproduce**
1. Add this to `.wslconfig`:
```
[wsl2]
networkingMode = mirrored
```
2. Use the snippets below :
```js
// main.js

const output = require('node:child_process').execSync("npm config get registry");
console.log(output.toString());
```
```jsonc
// launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach Program",
        }
    ]
}
```
3. Add a breakpoint to line 1 (`execSync()` line) in the program.
4. Now run the program, and attach to it:
```bash
NODE_OPTIONS="--inspect-brk" node ./main.js
```
5. Once the debugger is attached, press "Step over" and observe the program being hung.

In the background, node has started `npm config get registry`, but before the npm's node instance could run, node called the debugger code, and the debugger called `nc` command that is now hung waiting for a reply. On my system, it eventually resumes after the `nc` returns due to the (~2 mins) default timeout (?)

**VS Code:**
Version: 1.88.1 (user setup)
OS: Windows_NT x64 10.0.22631

**Comment by tusharsnx** [comment]
If you happen to have the PID of the attached node instance, you can run this command to see `nc` being stuck:
```bash
$ pstree -c -a -T -s <PID>
```

![image](https://github.com/microsoft/vscode-js-debug/assets/55626797/c857465a-1218-4b7a-acef-8c9bca27f5ba)

**Comment by connor4312** [comment]
Thanks for the investigation, I think this might have been the cause of another WSL we got recently. I'll look into a fix.

**Comment by connor4312** [comment]
This should be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension), please let me know whether this fixes it for your

**Comment by eleanorjboyd** [comment]
Hi @connor4312 - seems like there still exists an outstanding issue that @tusharsnx describes. Is another issue tracking this or should I reopen this issue? Thanks

**Comment by TylerLeonhardt** [comment]
reopening based on @tusharsnx's comment.

**Comment by connor4312** [comment]
Let's track that as a separate issue. The fix is still good for the original bug and I'm not sure I want to change it -- taking the performance hit for the pretty rare case of a higher privilege process listening on a high number port that we randomly pick.
