### ISSUE TITLE
Cannot find module bootloader.js

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#374]
Lately I've been getting this when trying to use the debugger (which now also doesn't work)
```
Error: Cannot find module '/Users/[User]/.vscode/extensions/ms-vscode.js-debug-nightly-2020.3.217/src/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1285:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:66:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

pwa-node doesn't work at all now :(
But i can't reproduce it on a public repo (it may not be related to the above)

**Comment by connor4312** [comment]
What does `ls ~/.vscode-insiders/extensions/ms-vscode.js-debug-nightly-2020.3.217/src` say? The bootloader file is present for me there, wonder if you got a corrupted install somehow.

**Comment by jasonwilliams** [comment]
It does show when I do that (which makes it more odd), so I’m not sure. I’ll see if it keeps happening, it can be inconsistent

**Comment by connor4312** [comment]
What might have happened is that the extension activated and was then updated without reloading / in another vscode window. Then the old extension folder was deleted, which caused the bootloader script disappeared. I can't seem to get into that state playing around locally, but that's one idea...

**Comment by jasonwilliams** [comment]
Yeah there’s a chance of that, is there a way for me to debug if that’s the case? I’ll look out for it again

**Comment by connor4312** [comment]
If you see it happen again, take note of the version in the path it's looking for, then open the extension panel in vscode and see what version of the extension it says is installed.

**Comment by phyllisstein** [comment]
I’m seeing something quite similar in my project. I’ve got a `tasks.json` file with the following configuration:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "start:dev",
      "problemMatcher": {
        "owner": "node",
        "fileLocation": "absolute",
        "pattern": {
          "regexp": "^🚨  (.*?):((\\d):(\\d):)? (.*)$",
          "line": 3,
          "column": 4,
          "file": 1,
          "message": 5
        },
        "background": {
          "activeOnStart": true,
          "beginsPattern": "^Server running at",
          "endsPattern": "^✨  Built in"
        }
      },
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": false
      },
      "label": "npm: start:dev",
      "detail": "Start the Parcel development server",
      "isBackground": true
    },
  ]
}
```

When I run the task, I see the following messages in VSCode’s terminal pane:

```
> Executing task: npm run start:dev <

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/var/folders/82/x75jd1fx0jj40t9s7tnghvxc0000gp/T/vscode-js-debug-bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1292:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

The same thing happens when I run an automatically detected and configured task:

```
> Executing task: npm run build <

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/var/folders/82/x75jd1fx0jj40t9s7tnghvxc0000gp/T/vscode-js-debug-bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1292:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

When I run the task with the Developer Tools open, I see the following logged to the browser console:

```
log.ts:197   ERR ioctl(2) failed, EBADF: Error: ioctl(2) failed, EBADF
    at UnixTerminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:238:13)
    at e.resize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3342:64)
    at e.setDimensions (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4344:261)
    at e._resize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4442:108)
```

I don’t really have a great sense of what all that could mean, I’m afraid. I can confirm that there is no `vscode-js-debug-bootloader.js` file in that temporary folder, but I’m not sure how to troubleshoot beyond that.

**Comment by connor4312** [comment]
Because this is happening in tasks, I think you're running into https://github.com/microsoft/vscode/issues/96375. You should be able to fix this by:

 1. Setting `debug.node.autoAttach` to "disabled" (to clear previous bad state)
 2. Setting it back to `on` or `off`, as you prefer
 3. Using the⚠️ icon on the top right to relaunch terminals as desired (or just reopen/reload VS Code)

**Comment by phyllisstein** [comment]
That did it! Thank you so much. I guess the two issues weren’t as similar as they looked. 🙊

**Comment by connor4312** [comment]
No worries, thanks for the detailed information 🙂

**Comment by jasonwilliams** [comment]
> Because this is happening in tasks, I think you're running into [microsoft/vscode#96375](https://github.com/microsoft/vscode/issues/96375). You should be able to fix this by:
> 
> 1. Setting `debug.node.autoAttach` to "disabled" (to clear previous bad state)
> 2. Setting it back to `on` or `off`, as you prefer
> 3. Using the⚠️ icon on the top right to relaunch terminals as desired (or just reopen/reload VS Code)

This would make a great FAQs answer

**Comment by connor4312** [comment]
The root cause got fixed in the commit that closed that bug, so it should not be an ongoing issue--this is the first report community report I've received of it so far 🙂

**Comment by connor4312** [comment]
I discovered another case where this can happen on extension version upgrade (https://github.com/microsoft/vscode/issues/96929). I applied a fix for it in the linked commit; you may see this one more time on the next version update, but after today's nightly (which will be version 2020.5.517) it should no longer be an issue.

**Comment by paulsimongb** [comment]
Tried that and I am still getting this error. I have checked the file system and the file exists, so can't it find it?

**Comment by connor4312** [comment]
See your issue here: https://github.com/microsoft/vscode/issues/101996

**Comment by rossmc** [comment]
Issue still occurs for me with latest stable version of node...
```
$ yarn
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '/var/folders/lp/_d8xd7zs60g73wlpxk2dwh_h0000gn/T/vscode-js-debug-bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1278:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
$ node -v
v12.18.2
```

**Comment by ochicf** [comment]
Started happening to me after updating VSCode to the latest version. I did not change the `launch.json` and it was working before.

The issue happens when opening a terminal in VSCode. The following error is thrown:

```
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/var/folders/4g/885bdns57cqf1cqzx8dw0vch0000gn/T/vscode-js-debug-bootloader.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:945:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:363:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:61:3)
    at internal/main/run_main_module.js:11:1
```

And I cannot use the terminal anymore as I guess the configuration is broken:

```
➜ node -v                           
zsh: command not found: node
➜ nvm current   
none
```

Information about my setup (from `About VSCode`):

```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

Some more info:

- I can run everything as normal from the non VSCode terminal (ex: from `iTerm2`)
- I can start a debug session from VSCode as usual and everything seems to be working great (breakpoints, variables, etc.)

**Comment by connor4312** [comment]
Please set `debug.node.autoAttach` to `disabled` for the moment. This will be fixed in the upcoming recovery release.

**Comment by mikeshot** [comment]
> Please set `debug.node.autoAttach` to `disabled` for the moment. This will be fixed in the upcoming recovery release.

Thank you! Having the same issue & this fixes the it (at least for now).

**Comment by amlcodes** [comment]
No luck at all, when launching debugger.

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '"/home/node/.vscode-server-insiders/bin/e7920dce7bfd0b707ebfc0a5379c6edd2233e475/extensions/ms-vscode.js-debug/src/bootloader.bundle.js"
```

launch.json

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "program": "${workspaceRoot}/src/index.js",
      "stopOnEntry": false,
      "args": [],
      "cwd": "${workspaceRoot}",
      "preLaunchTask": null,
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node",
      "runtimeArgs": [
        "--nolazy"
      ],
      "env": {
        "NODE_ENV": "development"
      },
      "console": "internalConsole",
      "sourceMaps": false,
      "outFiles": []
    }
  ]
}```

**Comment by connor4312** [comment]
@amlcodes you're hitting a version of https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666. The resolution steps in the comment will work for you (just ignore the electron part of it)

**Comment by aventurella-honey** [comment]
I'm seeing the same issue in 1.47.1.

```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```
When I launch the debugger in the integrated terminal I get the following error:
```
env 'NODE_OPTIONS=--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" 
```

^ this file exists

```
cat "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js"
```

But running my action yields this error, it's like the path isn't escaped?

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '"/Applications/Visual'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Setting `Debug > JavaScript: Use Preview` to `false` doesn't seem to fix it additionally setting `Debug: Node: Auto Attach" to `disabled` or toggling it from on/off -> disabled seems to have no affect. Restarting VS Code additionally doesn't seem to have any affect.

**Comment by connor4312** [comment]
@aventurella-honey your issue is https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666 (just ignore the electron part)

**Comment by Kristof-Mattei** [comment]
@connor4312  what do you mean by

> Using the⚠️ icon on the top right to relaunch terminals as desired (or just reopen/reload VS Code)
I don't see that icon?

**Comment by connor4312** [comment]
If you're on OSX or Linux (particularly if your machine crashed) you may be stuck and can follow the second set of instructions here: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

**Comment by superbizon2003** [comment]
Same problem with cyrillic username:
Error: Cannot find module 'c:/Users/�������_�/.vscode/extensions/ms-vscode.js-debug-nightly-2020.7.1617/src/bootloader.bundle.js'

**Comment by connor4312** [comment]
@superbizon2003 see here https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018

**Comment by superbizon2003** [comment]
> @superbizon2003 see here [#563 (comment)](https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018)

It worked! Thanks

**Comment by huixisheng** [comment]
```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (2 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0
```
with errors:
```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/var/folders/h9/53v387jx0mq2rrywyyjfzs1h0000gn/T/vscode-js-debug-bootloader.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:824:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by connor4312** [comment]
@huixisheng do you get that running things in the terminal? If so, you want to toggle auto attach to "disabled" and then back to on/off

**Comment by huixisheng** [comment]
> @huixisheng do you get that running things in the terminal? If so, you want to toggle auto attach to "disabled" and then back to on/off

yep, it works. thank you.

**Comment by rochdev** [comment]
I tried every possible combination of enabling/disabling auto attach and restarting VS Code and I still can't get rid of the issue. Anything else can be done other than switching to a nightly build?

**Comment by paulsimongb** [comment]
For me, it was upgrading Node to the latest version that cured it

**Comment by rochdev** [comment]
I get the same issue even after upgrading (just tried 12.16.1 which has been working for a while, 12.18.2 and 14.5.0). The issue started about 30 minutes ago, right after updating VS Code.

**Comment by connor4312** [comment]
Please share the error message you're receiving and your VS Code version.

**Comment by rochdev** [comment]
```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/var/folders/zh/6ycfn26d0hg_1njrc6lgbmyr0000gn/T/vscode-js-debug-bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1298:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:444:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:68:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by connor4312** [comment]
Please try these steps: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

**Comment by rochdev** [comment]
Did everything except installing VS Code Insider and I still get the same error.

**Comment by connor4312** [comment]
To be clear, when do you get that error? Is that whenever you run a Node command on the terminal, or only when debugging?

**Comment by rochdev** [comment]
Tried `node -v`, which worked, then tried again `yarn` and the error is gone. No idea why that is but at least it works now 😄

**Comment by connor4312** [comment]
Okay, cool. Note that the auto attach variables are set per-workspace, so you _may_ need to do the toggle in multiple folders to clear them out fully

**Comment by armchairdeity** [comment]
FYI - I had to do the trick with disabling `debug.node.autoAttach` just today with the current version (1.47.2).

And the issue I was having today really threw me for a loop, because it was when I was trying to build my Docker image... it turns out it was an error where `npm install` was actually the one throwing the error. And it was anything... nodemon, node, npm, even nvm didn't like whatever had happened.

What I know for sure is that the `debug.node.autoAttach` fix worked and I was glad. lol

**Comment by cmawhorter** [comment]
i just updated to 1.47.3 and was still seeing this issue. (missing is vscode-js-debug-bootloader.js)

the only thing that worked was setting debug.node.autoAttach to "disabled". 

and to people that were as dumb as me: "off" is not the same as "disabled". you must do this to actually disable auto attach:

- open .vscode/settings.json
- add option `"debug.node.autoAttach": "disabled"` 
- possibly restart vscode

after that the error went away.

**Comment by FickleLife** [comment]
I am getting this error for the last hour (was working fine before that?)

- node version: v14.6.0
- vscode: 1.47.3
- MacOS 10.15.6 (19G73)

I tried `"debug.node.autoAttach": "disabled"` (mine was already disabled) 
Hitting F5 yields:

```
/usr/local/bin/node /Users/user/Documents/flutter/thing/thing2/node index.js
Debugger listening on ws://127.0.0.1:50591/8b6e06d7-2c93-4f88-ac76-b996595e3cde
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module '/Users/user/Documents/flutter/thing/thing2/node index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Process exited with code 1

```
File is definitely located at the path mentioned....

**Comment by connor4312** [comment]
> /usr/local/bin/node /Users/user/Documents/flutter/thing/thing2/node index.js

It looks like you have Node trying to run Node... what's your launch conifg?

**Comment by FickleLife** [comment]
Thanks @connor4312, I just used the default `launch.json` and it seemed to add a `node ` at the start....

**Comment by mirzaumersaleem** [comment]
> Because this is happening in tasks, I think you're running into [microsoft/vscode#96375](https://github.com/microsoft/vscode/issues/96375). You should be able to fix this by:
> 
> 1. Setting `debug.node.autoAttach` to "disabled" (to clear previous bad state)
> 2. Setting it back to `on` or `off`, as you prefer
> 3. Using the⚠️ icon on the top right to relaunch terminals as desired (or just reopen/reload VS Code)

Resolved! , Thanks champ

**Comment by SebastiaoMoraes** [comment]
> Se você vir isso acontecer novamente, anote a versão no caminho que está procurando, abra o painel de extensão no vscode e veja a versão da extensão que está instalada.


It didn't work for me either. I still have debug unavailable

**Comment by SebastiaoMoraes** [comment]
Recebo.
![Error Vscode](https://user-images.githubusercontent.com/54009045/89192971-adb16800-d57b-11ea-8e31-f89ce1b3eda9.png)

**Comment by connor4312** [comment]
You're hitting https://github.com/microsoft/vscode-js-debug/issues/563

**Comment by SebastiaoMoraes** [comment]
> Você está atingindo [# 563](https://github.com/microsoft/vscode-js-debug/issues/563)

I still debug without working

**Comment by idoyana** [comment]
got the same issue here,
i'm using restart in launch configuration
and the issue happen only after the restart (when code changed)
![image](https://user-images.githubusercontent.com/1317547/89725284-81cc3180-da16-11ea-9dba-1bfd56ee6dd7.png)

here is the launch.json
![image](https://user-images.githubusercontent.com/1317547/89725299-a88a6800-da16-11ea-81af-9eeaa676dfe6.png)

i've tried to change the autoAttach to all different options - but the issue persist

**Comment by connor4312** [comment]
You can avoid that by setting `autoAttachChildProcesses: false`

**Comment by idoyana** [comment]
> You can avoid that by setting `autoAttachChildProcesses: false`

it is working! thanks a lot!

@connor4312 btw, i'm getting the following hint
![image](https://user-images.githubusercontent.com/1317547/89735036-55d99c00-da68-11ea-8ebb-e088644b6da4.png)

**Comment by connor4312** [comment]
You can get around that by setting the debug `type` to `pwa-node`. The `node` type goes to our "old" debugger, and its config schema doesn't know about our new option.

**Comment by amlcodes** [comment]
@connor4312  is that for both code and insiders? Or is `type: node` in insiders using the new debugger?

**Comment by connor4312** [comment]
It's for both stable and insiders.

**Comment by amlcodes** [comment]
@connor4312 not to get too off topic, but to clarify - I get a hint that `"type": "node",` is not allowed in my launch.json running insiders.

**Comment by tehpsalmist** [comment]
Is there a fix for this on the horizon? I'm just curious because I don't have time any more to run through all the permutations of solutions in this thread (often none of which work) just so I can run a terminal command that I can use iTerm for and just bypass the problem. Nevertheless, I do prefer to use the built-in terminal when I can. ¯\_(ツ)_/¯

**Comment by connor4312** [comment]
@tehpsalmist what issue are you hitting? There's quite a few different discussions in this thread 🙂

**Comment by tehpsalmist** [comment]
just every 3rd workspace I open has some kind of bootloader.js is missing error. It's been a couple months of this now, so I'm kind of hoping a fix is close. Sorry if this isn't my most productive comment. Here's my most recent error:

```sh
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/var/folders/cm/mkjr9w6557d0hwpy6vytw5mh0000gn/T/vscode-js-debug-bootloader.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:824:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I've also noticed that this only happens with certain commands (I believe only node cli tools, as git works fine in these messed up terminals).

**Comment by connor4312** [comment]
Okay, thanks. The solution for that issue is here: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467 If you're running the latest 1.48, you should only need to do these two steps to fix workspaces where you have this issue:

1. Set debug.node.autoAttach to "on". Wait a moment.
1. Set debug.node.autoAttach to "disabled". Wait a moment.
1. Open a new terminal, or reload the window.

**Comment by tehpsalmist** [comment]
So, this illustrates my point. I did those steps afresh now, at your advice. I am running 1.48.0, but it didn't work. Maybe I didn't "wait a moment" long enough? But I've been through this so many times that I'm done with it. It just needs to be fixed, no more workarounds. If you have news of when that fix might arrive, I'm curious to know. In the meantime, I'll just reach for other tools so I can get work done.

Sorry if this comes off as ungrateful, I do appreciate the hard work that your team is doing. VS Code is an amazing tool, and I'm sure it will continue to be. Thank you!

**Comment by connor4312** [comment]
The instructions linked are the fix; I haven't before received reports of them not working. Would you be willing to share a screen recording, or hop on a screenshare ([gifcap is good](https://gifcap.dev/)), so I can see exactly what you're doing / what's happening?

**Comment by tehpsalmist** [comment]
Sure, I can spare like 5 minutes

**Comment by connor4312** [comment]
Awesome, thanks, sent a Team invite to the email on your GH profile

**Comment by tehpsalmist** [comment]
Unfortunately, I'm still having trouble with this. For some reason, most of my workspaces have a non-working terminal and a handful of them work. I've tried the workarounds, and I've tried to replicate that process we (@connor4312 ) did over the screenshare where we installed a later version of the debugger and then turned the autoattach on/off. Either I just can't remember the correct debug package to do that with or the problem is not that uniformly distributed across my machine. Either way, I would really love to get this working again. Any advice is welcome, but ideally a future version of vs code will just have the proper migrations or fixes to make this a non-issue.

**Comment by connor4312** [comment]
The next version should have the fixes, to be released in about 1.5 weeks. We reintroduce this general strategy, but with many more safeguards and fixes -- tracked in https://github.com/microsoft/vscode-js-debug/issues/703

You can probably--I've not tested this--fix it globally by deleting (or renaming first, to be safe) your workspace storage folders to clear temp data. I believe by default on OSX this is `~/Library/Application Support/Code/User/workspaceStorage`

**Comment by tehpsalmist** [comment]
Ah, thank you, deleting that directory does seem to have brought a few workspaces back to working condition. If I find more that can't be fixed by the strategies listed above I'll report on it, but for now this seems to have straightened things out for me.

**Comment by jeffbski-rga** [comment]
I am having this error too with the August 2020 release. 

```
LSTL67fchtdd:~/projects/cloud-loadresults [sonar-2020-09-21]$ npm run test:unit
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/var/folders/m3/y7pcwbqj6nq9lrhmff598j74hgrysl/T/vscode-js-debug-bootloader.js'
```

If I run this in a iterm terminal outside of vscode then everything is fine, so this is something related to vscode.

I do not have the `~/Library/Application Support/Code/User/workspaceStorage` folder

**Comment by connor4312** [comment]
Any chance you have that left over from the June 2020 release? That problem was prevalent before the recovery release there but was fixed in the point release, and since then we'll no longer put the bootloader in a tmpdir.

Do these steps fix the issue? https://github.com/microsoft/vscode-js-debug/issues/374#issuecomment-675020979

**Comment by jeffbski-rga** [comment]
Yes, thanks @connor4312 that fixes it.

**Comment by rayhatfield** [comment]
I'm encountering a variation of this issue with a project that uses Node 10. I *think* what's happening is the plugin initializes against my default Node version (17.x or whatever) and decides spaces in paths are fine. Then I switch to 10.15 (via nvm) and it chokes on "Application Support":

```
⟩nvm use
Found '/path/to/project/.nvmrc' with version <10.15.1>
Now using node v10.15.1 (npm v)
internal/modules/cjs/loader.js:583                                                                                       
    throw err;
    ^

Error: Cannot find module '"/Users/ray/Library/Application'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:812:12)
    at preloadModules (internal/bootstrap/node.js:599:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

If I remove the `NODE_OPTIONS` environment variable the error goes away.

```
⟩echo $NODE_OPTIONS
--require "/Users/ray/Library/Application Support/Code/User/workspaceStorage/746f163c1fc90a7d6784a0a087d9f560/ms-vscode.js-debug/bootloader.js" 
```

If I disable auto-attach it goes away and I can live with that for now, but if someone has a better idea I'm open to suggestions.

**Comment by connor4312** [comment]
Yea, we don't have any way to detect nvm version changes. All Node version that don't support quotes (<12) are in [end of life](https://nodejs.org/en/about/releases/) so I do not plan to go through great lengths to discover a workaround for this.

**Comment by rayhatfield** [comment]
Understood. Posted mostly just to get confirmation that that is what's happening and I'm not missing some obvious fix, and to provide info for future VS Code archaeologists. Thanks.

**Comment by Porges** [comment]
I am getting this constantly, on multiple different codespaces/repos. Is there any current known issue?

**Comment by Porges** [comment]
If anyone else finds this, this comment has the solution: https://github.com/microsoft/vscode/issues/137794#issuecomment-978093998

**Comment by JustinGrote** [comment]
@Porges this fixes it temporarily but it happens on every codespaces rebuild. Is there a more permanent fix? I tried putting various autoattach settings into my devcontainer file with no luck.

**Comment by RaviPabari** [comment]
Faced same issue with 
```
❯ code --version
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
x64

OS: Linux Mint 20.3 x86_64 
Kernel: 5.4.0-124-generic
```


Unistalling and reinstalling fixed the problem for me.

**Comment by louwers** [comment]
Still running into this and none of the posted solutions seem to work.

I am not even trying to use the debugger, just using npm in the terminal.

**Comment by shemy-gan** [comment]
Linux: Ubuntu 20.04
Node 18.13
Vscode: 1.89.1

do a npm --version, getting below
Error: Cannot find module '/snap/code/155/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.js'
Require stack:
- internal/preload
double checked /snap/code/155, does not exist, I think it was removed by auto VSCode update as some point

**Comment by Austint30** [comment]
Hello,

Seems like this is still an issue in 2024. Getting this output after running `npm install <name>`:

```
node:internal/modules/cjs/loader:1189
  throw err;
  ^

Error: Cannot find module '/home/node/.vscode-server/data/User/workspaceStorage/9271fbbe3b75a285e8c4679515f8dd2a/ms-vscode.js-debug/bootloader.js'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1186:15)
    at Module._load (node:internal/modules/cjs/loader:1012:27)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1653:12)
    at loadPreloadModules (node:internal/process/pre_execution:687:5)
    at setupUserModules (node:internal/process/pre_execution:200:5)
    at prepareExecution (node:internal/process/pre_execution:153:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:52:10)
    at node:internal/main/run_main_module:13:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v22.2.0
```

Disabling and re-enabling auto attach fixes the issue temporarily, but I have to do this every time I start up the dev container.

**Comment by lamuertepeluda** [comment]
I am still having this issue for VSCode 1.91.1 on macOS Sonoma (Apple Silicon). 

Trying to debug some (rather complex) jest tests

```txt
Error: Jest: Got error running globalSetup - /usr/src/app/test/setup.ts, reason: Command failed: node -r ts-node/register ./src/cli.ts merge-openapi
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.js'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at internalRequire (node:internal/modules/cjs/loader:176:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1563:5)
    at loadPreloadModules (node:internal/process/pre_execution:730:5)
    at setupUserModules (node:internal/process/pre_execution:206:5)
    at prepareExecution (node:internal/process/pre_execution:159:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:54:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.15.1

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:338:12)
```

**Comment by nickjanssen** [comment]
This started to randomly happen to me after upgrading to Next 15. Disabling, restarting and then enabling the "javascript debugger" extension worked.

**Comment by dBianchii** [comment]
> This started to randomly happen to me after upgrading to Next 15. Disabling, restarting and then enabling the "javascript debugger" extension worked.

Thank you!! awesome happened with me after upgrading to Next 15

**Comment by thomasantony12** [comment]
I was using a remote SSH server to run the code and the error occurred to me. Following are the procedures which I used to resolve the problem.

## Manually Check for bootloader.js

1. Check if the bootloader.js file exists in the mentioned path:
    ```
    ls ~/.vscode-server/data/User/workspaceStorage/63314b8b92156532229f6a9bef0ab1d6/ms-vscode.js-debug/bootloader.js
    ```
2. If missing, manually reinstall the extension by clearing the cache:

    ```
    rm -rf ~/.vscode-server/extensions
    rm -rf ~/.vscode-server/data/User/workspaceStorage
    ```
3. Then reconnect using the Remote - SSH extension, which will reinstall all dependencies.

**Comment by daaain** [comment]
This happened to me and I was confused for a while until I realised it's because I'm running Next.js in a Docker container which obviously doesn't have VS Code inside. Gave up at this point, but might be possible to attach VS Code as a volume?
