### ISSUE TITLE
Allowing attaching to multiple pages that match the url filter

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#437]
Currently we stop trying to attach to pages once we get a page that matches our url filter. I think this is a limitation that should simply be removed.

Code pointer:

https://github.com/microsoft/vscode-js-debug/blob/3002a44a662792f0ccf350cd704f15a41d2f0163/src/targets/browser/browserTargets.ts#L109

cc @joaomoreno

**Comment by IllusionMH** [comment]
Do I understand correctly that it will produce picklist with all matched tabs as it works with `msedge` or `chrome` debuggers ATM?

**Comment by connor4312** [comment]
At the moment it will attach to the first target it sees, and ignore the remainder. Instead we should attach to any target that matches the url filter.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/commit/b6efe5b71ea8df5963ec597cec5ab4b807717679. By default on launching the URL filter will be set to the input URL, but you can set it to `*` which will attach to all pages that are ever created.

**Comment by IllusionMH** [comment]
Do you know when this change will be available in VS Code Insiders build to check it?

**Comment by connor4312** [comment]
Tomorrow or the day after, depending on timing; Insider builds are unscheduled during endgame.

**Comment by roblourens** [comment]
Now it shows the picker, and I select one, then it attaches to both anyway

![image](https://user-images.githubusercontent.com/323878/83801825-65ef8c80-a66f-11ea-9fc4-bc5b58c209f9.png)

![image](https://user-images.githubusercontent.com/323878/83801837-6a1baa00-a66f-11ea-9fa6-8a0a841caf85.png)

**Comment by connor4312** [comment]
@roblourens that doesn't happen for me. _However_ if one tab navigates / updates info, then we attach to it. I haven't yet implemented the banning mechanism described in #479 (opening an issue for that now...). Try some static pages, like github.com and google.com. Not sure if flights or trends might be doing weirder stuff.

Also note that clicking outside/cancelling the picker will attach to both, e.g. https://memes.peet.io/img/20-06-29a307d5-a73b-478c-bff2-80b9faaa9b2f.webm

**Comment by IllusionMH** [comment]
Should it be `"type": "chrome"` or `"pwa-chrome"`?
I have only later and I don't see picklist unless I specify `"targetSelection": "pick"` (same with `pwa-msedge`)

JavaScript Debugger (Nightly)
v2020.6.317

```json
{
    "type": "pwa-chrome",
    "request": "attach",
    "port": 9222,
    "name": "Attach Edge",
    // "targetSelection": "pick",
    "urlFilter": "example.com*",
    "webRoot": "${workspaceFolder}"
}
```

**Comment by connor4312** [comment]
The -found should be fixed with #505. Closing for next endgame verification.

> Should it be "type": "chrome" or "pwa-chrome"?

pwa-chrome if you're fine with that / not working on a project with other people using the previous set of debuggers.  If the [`usePreview` flag](https://github.com/microsoft/vscode-js-debug#----------------) is set (which is on by default in Insiders) then `type: chrome` will redirect to js-debug. However, the config's validation doesn't have js-debug's options so you'll get squiggly lines (all config options should still work though).

**Comment by roblourens** [comment]
Still seeing https://github.com/microsoft/vscode-js-debug/issues/437#issuecomment-639068519
