### ISSUE TITLE
Persist detached or un-picked tabs

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#505]
We allow picking as of https://github.com/microsoft/vscode-js-debug/issues/437 and #479. However if a target then changes its info, we'll attach to that (if it matches the URL filter). We should remember the 'banned' tabs and never attach to them.

**Comment by connor4312** [comment]
correction -- this doesn't happen on picking, but does on tab detachment

**Comment by connor4312** [comment]
To verify:

 1. Attach to a browser with multiple tabs open, e.g.

    ```
    {
      "type": "pwa-chrome",
      "request": "attach",
      "name": "attach to browser",
      "address": "127.0.0.1",
      "trace": true,
      "port": 9222,
      "urlFilter": "*"
    }
    ```

    When launching with --user-data-dir, e.g. `& "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir=C:\Users\Connor\Downloads\chrome-profile`

 2. Detach from one of the tabs
 3. Navigate around on that tab. VS Code should not re-attach to it.

**Comment by roblourens** [comment]
I think this is the same thing we saw when debugging today?

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/commit/050f4efbf73448ee7265c065be15e6416cb7e72d, good for verification in the next nightly/insiders :)

**Comment by aeschli** [comment]
Still seeing this in 1.47.0-insider (user setup)
Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
Date: 2020-07-02T05:48:37.715Z

also tried with `ms-vscode.js-debug-nightly` `v2020.7.117`.

Need to click on disconnect twice.

![recording (4)](https://user-images.githubusercontent.com/6461412/86374021-6128f300-bc84-11ea-9ae1-1682d8e60951.gif)

**Comment by connor4312** [comment]
@aeschli that's a different issue. The problem Rob was seeing was that disconnecting from a single tab would have no effect / immediately reconnect.

But having to disconnect twice is still weird. Can you share the launch config you're using?

**Comment by connor4312** [comment]
Re-closing for verification since your issue is different. But please do open a separate issue with your launch config. Thanks!

**Comment by aeschli** [comment]
@connor4312 What are the proper steps to verify?

**Comment by connor4312** [comment]
1. Connect to a browser with multiple tabs open matching your URL filter
1. Click the disconnect button on the (sub-)sessions for one of the tabs
1. That tab should be disconnected from. If you navigate the tab, it should not reconnect.
