### ISSUE TITLE
v4.12.9 broke, v.4.12.8 works

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-js-debug#678]
I keep it short cause I waste to much time reporting errors for to many extensions.

Ok, If I use v4.12.9 on mac I get:

```
Error processing launch: Error: Could not attach to main target
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:33351
	at async _.prepareLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2620406)
	at async _.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2621006)
	at async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25725)
	at async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25296)
	at async Promise.all (index 6)
	at async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:24556)
	at async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2459787)
```
I saw this post on stackoverflow:
https://stackoverflow.com/questions/63066518/visual-studio-debug-error-error-processing-launch-error-could-not-attach-to-m

I did this:

`In the section Extensions -> JavaScript Debugger set option Debug > JavaScript: Use Preview to false.`

And I downgraded to `4.12.8`, and now the extension works again.

I'm on OSX.

**Comment by connor4312** [comment]
In the linked StackOverflow, it looks like they're trying to debug a single HTML file which is fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). If this is not your issue, please collect a trace log using the following instructions:


>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by L0N** [comment]
I tried the suggestions here. I still get the same error.

I've installed v4.12.8 and I've also turned off JavaScript Preview.
I've attached my trace log
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/5087260/vscode-debugadapter-1.json.gz)

**Comment by connor4312** [comment]
@L0N please use the nightly built or update VS Code to 1.48.0 to get the fix.
