### ISSUE TITLE
New JavaScript Debugger stuck since VS Code version 1.47

### ISSUE THREAD

**Issue by iDschepe** [microsoft/vscode-js-debug#726]
Configuration in launch.json:
`
        {
            "name": "Attach to API Module",
            "type": "node",
            "request": "attach",
            "port": 9230,
            "restart": true,
            "sourceMaps": true,
            "protocol": "inspector",
            "timeout": 60000,
            "skipFiles": ["<node_internals>/**/*.js"],
            "trace": true,
        }
`

Starting node:
![2020-08-27 11_47_08-](https://user-images.githubusercontent.com/40547587/91426061-4629c800-e85c-11ea-9048-acacf5cb2986.png)

After attaching Debugger it shows:
![2020-08-27 11_50_51-GitHub - microsoft_vscode-js-debug_ The VS Code JavaScript debugger](https://user-images.githubusercontent.com/40547587/91426079-4c1fa900-e85c-11ea-8a8c-c082731f9cfa.png)

Then the console is stuck completely.
No breakpoint stops. 
Disconnect doesn't work.
The node server itself just works fine. 
With earlier Versions ( <= 1.46 ) debugging was possible. 

**Log File**
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/5135686/vscode-debugadapter-1.json.gz)

**VS Code Version:** 1.47

**Additional context**
Environment: 
Running VS Code in WSL on Windows 
`Linux 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by iDschepe** [comment]
**Update**
I deleted temporarily the launch.json.
I tried to create a new launch.json with one single config -> no success

After that I delete launch.json again.
And I've found a workaround.

After that I tried this:
![image](https://user-images.githubusercontent.com/40547587/91442967-f1de1280-e872-11ea-8748-39bb7a3fec2f.png)
If I start this:
![image](https://user-images.githubusercontent.com/40547587/91443493-b55ee680-e873-11ea-8bbe-fe6a495bda3a.png)
Many "Debugger attached" lines appear in the console...
![image](https://user-images.githubusercontent.com/40547587/91444120-96148900-e874-11ea-9d69-fbb2af6d5ed6.png)
and finally, I was able to debug.

What is the difference in launching via launch.json and "Run script: xxx" debugging.
Refer to: https://github.com/microsoft/vscode-js-debug#easy-npm-script-debugging

If you need any further information, feel free to contact me. 
BR Mario

**Comment by connor4312** [comment]
Thanks for the issue. What version of Node.js are you using?

**Comment by iDschepe** [comment]
Hi connor4312, I am using v12.18.3.

**Comment by connor4312** [comment]
Hm, okay. This looks like https://github.com/microsoft/vscode-js-debug/issues/649 -- for them, updating to a recent Node version fixed the issue. If you're able to, could you try updating (latest version is 14.7.0) and see if that fixes the issue?

**Comment by iDschepe** [comment]
Hi, I tried to update and use the latest version of node (14.10.1).
Unfortunately in my project I am strictly bound to the latest LTS version of Node (12).
Is there anything else I could try / do?

**Comment by EugenIvanou** [comment]
I can confirm that even 'hello world' example from https://code.visualstudio.com/docs/editor/debugging and [youtube tutorial (0-1:20)](https://www.youtube.com/watch?v=2oFKNL7vYV8) doesn't work as described with node v10 using nvm, but works fine with v12 also with nvm on ubuntu 18.04. For me it's not solution to switch for the new version of nodejs.
`Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-118-generic`

**Comment by connor4312** [comment]
@EugenIvanou please collect a trace log using the instructions in the issue template:



>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by EugenIvanou** [comment]
@connor4312 thanks, for the answer, the trace below
[vscode-debugadapter-3.json.gz](https://github.com/microsoft/vscode-js-debug/files/5301050/vscode-debugadapter-3.json.gz)

**Comment by connor4312** [comment]
Thanks, I see you're running nvm, so are you able to easily try on the latest 10.x, e.g. `10.22.1`? If I recall there were a couple point releases in 10.x where things were broken, though I don't reproduce any issues on Ubuntu running 10.16.0 myself.

**Comment by EugenIvanou** [comment]
@connor4312 I've checked 10.22.1 and it's working fine, thanks.

**Comment by connor4312** [comment]
Okay, gotcha. I'll add that to our COMMON_PROBLEMS.md -- this had come up before but I couldn't find the issue. Glad you got it working. @iDschepe that may be what you're hitting as well.

**Comment by connor4312** [comment]
Also, @iDschepe I just saw that you're on a pretty old release. I would update to a recent VS Code release, we've made dozens of fixes since the new debugger first debuted in 1.47. There's a decent chance that what you're hitting was already fixed.

**Comment by iDschepe** [comment]
Hi @connor4312, 
thanks for coming back. I updated VS Code to the latest, unfortunately I still get the same issue. 
![image](https://user-images.githubusercontent.com/40547587/95969391-f2287200-0e0e-11eb-9bf8-c66b6fcb3627.png)

**Comment by connor4312** [comment]
Hm, okay. From what you shared previously, this seems like either some issue in Node.js or (less likely) some esoteric firewall/proxy problem, so I'm not sure if there's more we can do here.

**Comment by ret394** [comment]
I was about to add a tip to avoid this entire class of problems. But looking at vscode repo issues and #649, the always angry mob of stupid people has excoriated many VSCode devs for trivial nonsense.

This is a transmutated part of a 58 page preliminary report. Or 50 pages if you're hooked into it, but don't like numbers larger than 50.

---

For the common people, about 10 000 pops minimum (majority of people) that forget to post debug logs options - add a bot. It's a better solution than issue templates.

What I mean by add a bot. For example - If Mr. Slavoy Zishek is in a hurry and doesn't have the time to read it - 1. **He can just nuke the stupid issue template**. 2. Get back and worry if he did something stupid. 3. Maintainer comes off out of extremely high-pressure zones points and point to the issue template. 4. Maybe, the author bothers to find the issue template. 5. Then a long period of ...
<snipped>

Not like the vscode bot, setup permissions to allow new users to just help themselves.

Okay if you ignore the multiple copies of the same post interspersed with different comments. 
But hey! it's better than being kicking yourself to post the same comments in a single thread.  (narration -author escapes the hard questions. How, you ask, answer is like a 🐱‍👤 )

And if you use a modified, bespoke version of Typescript (that cannot be merged back to Microsfot's repo due to different project goals) it definitely scales well on Github - `call it state of the art Git Scale bot` in one of the posts of the official blurb site.

---

> https://github.com/microsoft/vscode-js-debug#easy-npm-script-debugging

That's independent of VSCode, consequently quite helpful in debugging crazy, wonderful issues from Oogway.
Just build a 2nd level debugger ( debugger debugger ) and you'll understand it. Wait till you build a 3rd level debugger for a monolithic open-source kernel, I haven't dared to do that ever, not even in my imagination.

---

Link to VSCode Repo bot - https://github.com/vscode-triage-bot
Hmm... 
> GPU-powered Azure VM

sounds pretty dumb, but I do not know much about GPUs or deep learning. I though I would have to immediately brush up on sklearn but I guess it's not that good for a few ... well, it was hilarious classifier code. And informative cintel for me, though not in the traditional sense of the word.

**Comment by ret394** [comment]
Don't update to latest VSCode 1.x.0 version. If you are on crunch time.

If you want a random range for debugger issues try 1.37 to 8.0531853

you're welcome, as always. all the best. 👍
don't say '... passim' to folks on Github or other sites.

[ret394](https://github.com/ret394)

**Comment by connor4312** [comment]
@ret394 if you are running into a problem, please open a new issue using the template. I invite you to also read through the [Microsoft OSS Code of Conduct](https://opensource.microsoft.com/codeofconduct/) under which is this project and others are governed. Thanks!

**Comment by ret394** [comment]
Too tired for answering that properly @connor4312, feel free to delete the comment in the time period. I'm not pedantic about trifles.

thanks. keep up the good part of your work. 👍

**Comment by connor4312** [comment]
I am going to close this issue. It seems like the issue reporter found a workaround, and the initial bug appears to be an issue in Node.js. I haven't been able to reproduce this locally and the issue reporter isn't able to update, so I don't want to upstream this issue to Node when it's reported on both and old version and without reproducible steps.

If, when you are eventually able to update Node, you still run into this problem, let me know and I can help investigate future and raise an issue with the Node team.
